method: Method
mode: "train"
weight: []
use_randomseed: False
seed: 1
data_root_dir: "/root/hdd1"
dev_root_dir: "/root/dev"
device:
  use_gpu: True
  num_workers: 16
  cudnn_benchmark: True
  cudnn_deterministic: False
distributed:
  use_ddp: False
  num_gpus: 1
  OMP_NUM_THREADS: 12
data:
model:
  latent_input:
    method: VAE
    arch:
      latent_encode:
        module: ARTransformer
        loss: Null
  generator:
    method: Generator
    arch:
      backbone:
        module: ARTransformer
        loss: Null
      shape_gen:
        module: ShapeDecoder
        loss: Null
      render:
        module: Proj2Img
        loss: KL
        weight: 1
optimizer:
  type:
  method:
  lr: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0
  clip_norm: -1
scheduler:
  latent_input:
    milestones: [400]
    gamma: 0.1
bnscheduler:
  bn_decay_step: 20
  bn_decay_rate: 0.5
  bn_momentum_init: 0.5
  bn_momentum_max: 0.001
train:
  batch_size: 256
  epochs: 500
  epochs_latent: 50
  freeze: []
  clip_norm: False
eval:
  batch_size: 1
  epochs: 500
log:
  exp_name: "Method_${mode}_${now:%Y-%m-%d}/${now:%H-%M-%S}"
  log_dir: "${data_root_dir}/Method/exps/"
  use_wandb: False
  print_model: False
  print_step: 1
  vis_step: 100
# hydra
hydra:
  run:
    dir: ${log.log_dir}
defaults:
  # - hydra/launcher: submitit_slurm
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_